### ISSUE TITLE
Use Jmol/JSmol on iOS

### ISSUE THREAD

**Issue by Yike-Ye** [BobHanson/Jmol-SwingJS#21]
I saw on your website, your team said JSmol could be used with html5 on iOS and Android. But I don't know how to install or use it. Besides, it seems that some apps on iOS can support javascript, so can I use Jmol with these apps?

**Comment by BobHanson** [comment]
There should be no issue with running JavaScript on Android systems. Basically the same as on other machines, but you may want to be sure the page is adaptive to size. for example: https://sharemol.com/    See the JSmol wiki for more information.
