### ISSUE TITLE
Local files fail to load via the menu bar

### ISSUE THREAD

**Issue by vaitkus** [BobHanson/Jmol-SwingJS#33]
The issue manifests at least since version 14.32.79.
The issue was not present in version 14.32.77.

I noticed the issue while using the Jmol version downloaded from SourceForge full-tar.gz [1]. I have not tried compiling the source code, but I am willing to do so if you cannot reproduce the issue. Tested on LinuxMint 21 with openjdk version "11.0.16" 2022-07-19.

Steps to reproduce the issue:
1. Download and extract the tar.gz file.
2. Go to the jmol-14.32.79-full/jmol-14.32.79 directory.
3. Run the "../jmol" script (script resides in the parent directory of the current working directory).
4. In the menu bar click File -> Open and select the file to open.

The selected file fails to load properly (no atoms appear) and the program itself seems to get stuck in a strange state, i.e. the "Get PDB" options fails to open, right clicking the view window opens a menu with  the molecule editing functionality instead of the expected regular one, etc. Tested by trying to load CIF and SDF files that work perfectly fine on earlier versions.

What is more, loading files in an alternative way do not produce the same issues. For example, a freshly started program can properly load the same file by right clicking the view window and selecting File->Load->Open local file options.

Please let me know if you can reproduce the issue and if you need any additional information.

[1] https://sourceforge.net/projects/jmol/files/Jmol/Version%2014.32/Jmol%2014.32.79/

**Comment by BobHanson** [comment]
OK, that is re-released.

On Thu, Oct 27, 2022 at 10:48 AM Robert Hanson ***@***.***> wrote:

> Indeed. I have deleted that release and will replace it shortly.
>


-- 
Robert M. Hanson
Professor of Chemistry
St. Olaf College
Northfield, MN
http://www.stolaf.edu/people/hansonr


If nature does not answer first what we want,
it is better to take what answer we get.

-- Josiah Willard Gibbs, Lecture XXX, Monday, February 5, 1900

*We stand on the homelands of the Wahpekute Band of the Dakota Nation. We
honor with gratitude the people who have stewarded the land throughout the
generations and their ongoing contributions to this region. We acknowledge
the ongoing injustices that we have committed against the Dakota Nation,
and we wish to interrupt this legacy, beginning with acts of healing and
honest storytelling about this place.*

**Comment by vaitkus** [comment]
Thank you for a quick fix. Tested the new release, works as expected now.
