### ISSUE TITLE
customize colors for structure

### ISSUE THREAD

**Issue by wunderbarr** [BobHanson/Jmol-SwingJS#46]
Hello,

I download the latest verstion of Jmol and extract JSmol from sourceforge.

Not sure whether I should use library from sourceforge or use this Jmol-SwingJS library.

Currently I use the sourceforge one and want to customize colors for a structure.

I wrote the following code, but the customization does not work, it still displays the default color setup.

```
			Jmol.script(jsmolApplet, "wireframe off; spacefill off; ");
			Jmol.script(jsmolApplet, "cartoon on");
			Jmol.script(jsmolApplet, "color cartoon structure");
			Jmol.script(jsmolApplet, "spin on");
			Jmol.script(jsmolApplet, "select all; color cartoon [FFFFFF]");
			Jmol.script(
				jsmolApplet,
				"select protein and helix; color cartoon [FFA500]"
			);
			Jmol.script(
				jsmolApplet,
				"select protein and sheet; color cartoon [FFFF00]"
			);
			Jmol.script(
				jsmolApplet,
				"select not helix and not sheet; color cartoon [0000FF]"
			);
```
I am not sure whether I am using the correct library.

Do you have any idea about that?

Thank you!

**Comment by gutow** [comment]
Now I see it your rgb colors need to begin with an "x". For example "color cartoon [xFFA500]" should work.

**Comment by BobHanson** [comment]
Also, just a comment that it is way more efficient to group your script
commands together into a single string with semicolons. No real issue, just
simpler all around.

Jmol.script(jsmolApplet, "wireframe off; spacefill off;"
			+ "cartoon on;"
			+ "color cartoon structure;"
			+ "spin on;"
			+ "select all; color cartoon [xFFFFFF];"
			+ "select protein and helix; color cartoon [xFFA500];"
			+ "select protein and sheet; color cartoon [xFFFF00];"
			+ "select not helix and not sheet; color cartoon [x0000FF];"
			);
